### 获取用户作为管理员或域主的群的加入请求
GET http://localhost:8888/group/pendingJoinRequests
Content-Type: application/json

{
  "jwt": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMjM0NTYiLCJ1aWQiOjEwMDAwMCwiaWF0IjoxNzIwOTY3OTU5LCJleHAiOjE3MjEwNTQzNTl9.HE06xWSsYWmvarGubjNr75pn84r_4doIk3QAu94LueyhVFMy3FnB5hGhy7oSRV5p",
  "uid": 100000
}
