spring:
  application:
    name: demo
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000  # 30 seconds
      max-lifetime: 60000  # 60 seconds
      connection-timeout: 30000  # 30 seconds
      connection-test-query: SELECT 1

    chat-user:
      url: jdbc:mysql://47.109.199.76:3306/chat_user
      username: test
      password: testtest
      driver-class-name: com.mysql.cj.jdbc.Driver
    chat-group:
      url: jdbc:mysql://47.109.199.76:3306/chat_group
      username: test
      password: testtest
      driver-class-name: com.mysql.cj.jdbc.Driver


# 控制台日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: 42835051ca12dbdb17eacfbcae4a297220db807ad9c3a6762495e648ade8e117



logging:
 level:
   root: DEBUG
   org.springframework: DEBUG
   org.apache: DEBUG
