### Register a new user
POST http://localhost:8888/api/user/register
Content-Type: application/json

{
  "username": "test3",
  "password": "123456",
  "email": "test3@example.com",
  "gender": "female"
}
