### Register a new user
POST http://localhost:8888/api/user/register
Content-Type: application/json

{
  "username": "test1",
  "password": "testtest",
  "email": "test@example.com",
  "gender": "female"
}
