### Get User Groups
GET http://localhost:8888/api/user/getgroup
Content-Type: application/json

{
  "uid": 100000,
  "jwt": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMjM0NTYiLCJ1aWQiOjEwMDAwMCwiaWF0IjoxNzIwOTY4OTI4LCJleHAiOjE3MjEwNTUzMjh9.hcgYnv5fyOLtItz-wdP3ryqwLc8oT0HSn9rMubBB7ppK_UB25HHcw0TX7DwPp49-"

}