### 用户登录
POST http://47.109.199.76:8888/api/user/login
Content-Type: application/json

{
  "uid": "100000",
  "password": "#36041322107nbti"
}

### jwt
eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXBwbGFuZCIsInVpZCI6MTAwMDAwLCJpYXQiOjE3MjA4NzAyNTcsImV4cCI6MTcyMDk1NjY1N30.hIAifIKz6cNRHCXPvnoo4vEHjF7AW3qB20163beqK3G6COjI8_uTkAvhOcVOlPXL
