### 用户登录
POST http://localhost:8888/api/user/login
Content-Type: application/json

{
  "uid": "100000",
  "password": "#36041322107nbti"
}

### jwt
eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXBwbGFuZCIsInVpZCI6MTAwMDAwLCJpYXQiOjE3MjA4ODY2MzksImV4cCI6MTcyMDk3MzAzOX0.J-t1qOYU-j-Hd5azP3D8_v8SnJJLetPlQ9XT-o9qGQcGy1j1Qp-T5HGbIW8jX_80
