### 用户登录
POST http://localhost:8888/api/user/login
Content-Type: application/json

{
  "uid": "100000",
  "password": "123456"
}

### jwt
eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0XzEiLCJ1aWQiOjEwMDAwMCwiaWF0IjoxNzIwOTc3MDI0LCJleHAiOjE3MjEwNjM0MjR9.9Tu-u8hayVpClUpxVfj1Csvx5OQDBnBVmfHYjOXDAc6s-3L8T5PzwolHYGStx7LG
