### Register a new user
POST http://localhost:8888/api/user/register
Content-Type: application/json

{
  "username": "Mappland1",
  "password": "#36041322107nbti",
  "email": "mapplandli@gmail.com",
  "gender": "female"
}
